server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://149.88.75.107:3306?useSSL=false&serverTimezone=UTC
    username: root
    password: Admin#123..
    driver-class-name: com.mysql.cj.jdbc.Driver


